### ISSUE TITLE
LUA_OK没定义吧?

### ISSUE THREAD

**Issue by lifefloating** [cloudwu/lua-bson#12]
编译时error

bson.c: In function ‘lencode’:
bson.c:975:31: error: ‘LUA_OK’ undeclared (first use in this function)
  if (lua_pcall(L, 2, 1, 0) != LUA_OK) {
                               ^
bson.c:975:31: note: each undeclared identifier is reported only once for each function it appears in
bson.c: In function ‘lencode_order’:
bson.c:1007:33: error: ‘LUA_OK’ undeclared (first use in this function)
  if (lua_pcall(L, n+1, 1, 0) != LUA_OK) {
                                 ^
bson.c: At top level:
bson.c:1293:12: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘int’

**Comment by cloudwu** [comment]
http://www.lua.org/manual/5.3/manual.html#pdf-LUA_OK
