### ISSUE TITLE
疑似发现encode lua_Integer判断是否是int32还是int64的地方有bug

### ISSUE THREAD

**Issue by tzngit** [cloudwu/lua-bson#3]
LUA_VERSION_NUM >= 503的那个```append_number```函数里在判断从lua stack上读取的lua_Integer是int32还是int64的判断，貌似有点问题啊，代码如下：

        int64_t i = lua_tointeger(L, -1);
		int si = i >> 31;
		if (si == 0 || si == -1) {
			append_key(bs, BSON_INT32, key, sz);
			write_int32(bs, i);
		} else {
			append_key(bs, BSON_INT64, key, sz);
			write_int64(bs, i);
		}

仅通过```(si == 0 || si == -1) ```这个判断不能说明```i```就是一个int32吧，比如```i = 0x8000000000000000``` 这种情况虽然右移31位的结果是0 但是```i```是一个64位整数，实际测试了下结果也是这样，不知道是不是我理解错了。

**Comment by cloudwu** [comment]
好像应该是 >> 32

**Comment by tzngit** [comment]
是的 >>32是对的，或者 ```( i > INT_MAX || i < INT_MIN)``` 不过没有移位操作效率高，最近在看大神代码，觉得有好多地方可以学习的！:+1:

**Comment by cloudwu** [comment]
ps. 这个 bug 是这样来的. 最早的版本是为 lua 5.2 做的, lua5.2 最多能表示 52bit 的 integer, 所以 >> 31 没有关系

后来改到 lua 5.3 就直接抄过来了.

和 INT_MAX  INT_MIN 比较意义更明确一些.
